on:
  workflow_call:
    inputs:
      buildjet-runs-on:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
env:
  GST_VERSION: "1.22.8"
  LIBNICE_VERSION: "0.1.21"

jobs:
  base-gstreamer-build:
    runs-on: ${{ inputs.buildjet-runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base
        uses: docker/build-push-action@v5
        with:
          context: ./build/gstreamer
          push: true
          build-args: |
            GSTREAMER_VERSION=${{ env.GST_VERSION }}
            LIBNICE_VERSION=${{ env.LIBNICE_VERSION }}
          file: ./build/gstreamer/Dockerfile-base
          tags: livekit/gstreamer:${{ env.GST_VERSION }}-base

      - name: Build and push dev
        uses: docker/build-push-action@v5
        with:
          context: ./build/gstreamer
          push: true
          build-args: |
            GSTREAMER_VERSION=${{ env.GST_VERSION }}
            LIBNICE_VERSION=${{ env.LIBNICE_VERSION }}
          file: ./build/gstreamer/Dockerfile-dev
          tags: livekit/gstreamer:${{ env.GST_VERSION }}-dev

      - name: Build and push prod
        uses: docker/build-push-action@v5
        with:
          context: ./build/gstreamer
          push: true
          build-args: |
            GSTREAMER_VERSION=${{ env.GST_VERSION }}
            LIBNICE_VERSION=${{ env.LIBNICE_VERSION }}
          file: ./build/gstreamer/Dockerfile-prod
          tags: livekit/gstreamer:prod-${{ env.GST_VERSION }}-prod

      - name: Prune docker state
        run: docker rmi livekit/gstreamer:${{ env.GST_VERSION }}-prod

      - name: Build and push prod RS
        uses: docker/build-push-action@v5
        with:
          context: ./build/gstreamer
          push: true
          build-args: |
            GSTREAMER_VERSION=${{ env.GST_VERSION }}
            LIBNICE_VERSION=${{ env.LIBNICE_VERSION }}
          file: ./build/gstreamer/Dockerfile-prod-rs
          tags: livekit/gstreamer:${{ env.GST_VERSION }}-prod-rs
