name: Publish GStreamer

on:
  workflow_dispatch:
    inputs:
      version:
        description: "GStreamer version to publish (e.g. 1.24.4)"
        required: true
        type: string

jobs:
  gstreamer-build-amd64:
    uses: ./.github/workflows/publish-gstreamer-base.yaml
    with:
      version: ${{ inputs.version }}
      buildjet-runs-on: buildjet-8vcpu-ubuntu-2204
      arch: amd64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  gstreamer-build-arm64:
    uses: ./.github/workflows/publish-gstreamer-base.yaml
    with:
      version: ${{ inputs.version }}
      buildjet-runs-on: namespace-profile-arm-16
      arch: arm64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  tag-gstreamer-build:
    needs: [gstreamer-build-amd64, gstreamer-build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run tag script
        run: ./build/gstreamer/tag.sh ${{ inputs.version }}
